### ISSUE TITLE
Share your Contact Info?

### ISSUE THREAD

**Issue by mbcrump** [TomasFilipCZ/PS4-USB-HEN-ESP8266Control#1]
I'm interested in chatting with you about this but can't find a way to connect. I'm on Discord mbcrump#1958 or twitter crump_youtube.

**Comment by TomasFilipCZ** [comment]
Hello Michael, 

it's my pleasure you contacted me. I'm updated github with discord server link and I follow you on twitter, as I'm like your technical video's. Sure happy to answer anything you interested it. You can contact me by email,  tomas.filip.CZ@gmail.com as is now email contact stated in GIT
